name: The Web I Know
description: A Blog About Web Development
meta_description: ""

markdown: kramdown
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.thewebiknow.com'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://www.thewebiknow.com'
author:         'Michael Leff'
